### ISSUE TITLE
Installing optifine through the menu button causes a crash on restart

### ISSUE THREAD

**Issue by MrGreenTea** [evanbones/sugarandspice#1]
Thanks for the beautiful mod pack!
I wanted to use the shaders and get the perfomance benefits as well so tried installing `Optifine`.
I tried through the button in the menu as well as manually downloading it from the official site and putting it in the `mods` folder. I tried versions `G8` and `G7`.

<details>
  <summary>Here is the output of `latest.txt`</summary>

```
[05Nov2021 11:11:42.486] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, mrlordalfred, --version, 1.16.5, --gameDir, ..\..\instances\Sugar and Spice, --assetsDir, ..\..\datastore\assets, --assetIndex, 1.16, --uuid, 2ae7a830285e474dae7535424b04883f, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.4, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[05Nov2021 11:11:42.489] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_242 by AdoptOpenJDK
[05Nov2021 11:11:42.637] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[05Nov2021 11:11:42.639] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\jonas\AppData\Roaming\gdlauncher_next\instances\Sugar and Spice\mods\OptiFine_1.16.5_HD_U_G8.jar
[05Nov2021 11:11:42.641] [main/INFO] [optifine.OptiFineTransformer/]: Target.PRE_CLASS is available
[05Nov2021 11:11:42.711] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[05Nov2021 11:11:42.740] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/jonas/AppData/Roaming/gdlauncher_next/datastore/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[05Nov2021 11:11:42.745] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[05Nov2021 11:11:44.416] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[05Nov2021 11:11:44.431] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[05Nov2021 11:11:44.444] [main/INFO] [optifine.OptiFineTransformer/]: Targets: 311
[05Nov2021 11:11:44.850] [main/INFO] [optifine.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[05Nov2021 11:11:44.899] [main/ERROR] [mixin/]: Mixin config modernworldcreation.mixin.json does not specify "minVersion" property
[05Nov2021 11:11:44.970] [main/ERROR] [mixin/]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
[05Nov2021 11:11:45.001] [main/ERROR] [mixin/]: Mixin config drippyloadingscreen.mixin.json does not specify "minVersion" property
[05Nov2021 11:11:45.148] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [org.infernalstudios.infernalexp.mixin.MixinConnector]
[05Nov2021 11:11:45.150] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [me.treyruffy.betterf3.betterf3forge.BetterF3MixinConnector]
[05Nov2021 11:11:45.151] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.blackgear.cavesandcliffs.mixin.CCBMixinConnector]
[05Nov2021 11:11:45.152] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [com.fuzs.consoleexperience.mixin.MixinConnector]
[05Nov2021 11:11:45.153] [main/INFO] [BetterF3/]: Invoking Mixin Connector
[05Nov2021 11:11:45.168] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.5, --gameDir, ..\..\instances\Sugar and Spice, --assetsDir, ..\..\datastore\assets, --uuid, 2ae7a830285e474dae7535424b04883f, --username, mrlordalfred, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 854, --height, 480]
[05Nov2021 11:11:45.255] [main/INFO] [Forgery/]: Reloading configs...
[05Nov2021 11:11:45.285] [main/INFO] [Forgery/]: Loading of features.ini done in 13.66 ms with 0 warnings
[05Nov2021 11:11:45.286] [main/WARN] [Forgery/]: Forgery is about to inject into Mixin to add support for failsoft mixins.
[05Nov2021 11:11:45.286] [main/WARN] [Forgery/]: THE FOLLOWING WARNINGS ARE NOT AN ERROR AND DO NOT IMPLY FORGERY IS RESPONSIBLE FOR A CRASH.
[05Nov2021 11:11:45.313] [main/WARN] [mixin/]: Overriding InjectionInfo for @Inject with com.unascribed.fabrication.support.injection.FailsoftCallbackInjectionInfo (previously org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo)
[05Nov2021 11:11:45.318] [main/WARN] [mixin/]: Overriding InjectionInfo for @ModifyArg with com.unascribed.fabrication.support.injection.FailsoftModifyArgInjectionInfo (previously org.spongepowered.asm.mixin.injection.struct.ModifyArgInjectionInfo)
[05Nov2021 11:11:45.322] [main/WARN] [mixin/]: Overriding InjectionInfo for @ModifyArgs with com.unascribed.fabrication.support.injection.FailsoftModifyArgsInjectionInfo (previously org.spongepowered.asm.mixin.injection.struct.ModifyArgsInjectionInfo)
[05Nov2021 11:11:45.325] [main/WARN] [mixin/]: Overriding InjectionInfo for @Redirect with com.unascribed.fabrication.support.injection.FailsoftRedirectInjectionInfo (previously org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo)
[05Nov2021 11:11:45.331] [main/WARN] [mixin/]: Overriding InjectionInfo for @ModifyVariable with com.unascribed.fabrication.support.injection.FailsoftModifyVariableInjectionInfo (previously org.spongepowered.asm.mixin.injection.struct.ModifyVariableInjectionInfo)
[05Nov2021 11:11:45.338] [main/WARN] [mixin/]: Overriding InjectionInfo for @ModifyConstant with com.unascribed.fabrication.support.injection.FailsoftModifyConstantInjectionInfo (previously org.spongepowered.asm.mixin.injection.struct.ModifyConstantInjectionInfo)
[05Nov2021 11:11:45.339] [main/WARN] [Forgery/]: Injection complete.
[05Nov2021 11:11:45.349] [main/WARN] [SodiumConfig/]: No configuration key exists with name 'mixin.ai', ignoring
[05Nov2021 11:11:45.349] [main/WARN] [SodiumConfig/]: No configuration key exists with name 'mixin.ai.poi', ignoring
[05Nov2021 11:11:45.350] [main/INFO] [Sodium/]: Loaded configuration file for Sodium: 24 options available, 2 override(s) found
[05Nov2021 11:11:45.385] [main/WARN] [mixin/]: Reference map 'yungsbridges.refmap.json' for yungsbridges.mixins.json could not be read. If this is a development environment you can ignore this message
[05Nov2021 11:11:45.431] [main/WARN] [mixin/]: Reference map 'nethers_delight.refmap.json' for nethers_delight.mixins.json could not be read. If this is a development environment you can ignore this message
[05Nov2021 11:11:45.796] [main/INFO] [net.minecraftforge.coremod.CoreMod.placebo/COREMODLOG]: Patching ModelBakery#<init>
[05Nov2021 11:11:45.947] [main/INFO] [net.minecraftforge.coremod.CoreMod.placebo/COREMODLOG]: Patching LivingEntity#attackEntityFrom
[05Nov2021 11:11:46.134] [main/INFO] [net.minecraftforge.coremod.CoreMod.placebo/COREMODLOG]: Patching LivingEntity#attackEntityFrom
[05Nov2021 11:11:46.182] [main/WARN] [Sodium/]: Force-disabling mixin 'features.item.MixinItemRenderer' as rule 'mixin.features.item' (added by mods [quark]) disables it and children
[05Nov2021 11:11:46.188] [main/WARN] [Sodium/]: Force-disabling mixin 'features.world_ticking.MixinClientWorld' as rule 'mixin.features.world_ticking' (added by mods [abnormals_core]) disables it and children
[05Nov2021 11:11:46.478] [main/WARN] [mixin/]: @Mixin target net/minecraft/world/gen/feature/structure/MineshaftPieces$Piece is public in supplementaries.mixins.json:accessors.MineshaftAccessor and should be specified in value
[05Nov2021 11:11:46.660] [main/WARN] [mixin/]: Error loading class: biomesoplenty/common/world/BOPBiomeProvider (java.lang.ClassNotFoundException: null)
[05Nov2021 11:11:46.661] [main/WARN] [mixin/]: Error loading class: xiroc/dungeoncrawl/dungeon/Dungeon (java.lang.ClassNotFoundException: null)
[05Nov2021 11:11:47.031] [main/INFO] [net.minecraftforge.coremod.CoreMod.placebo/COREMODLOG]: Patching ItemStack#onItemUse
[05Nov2021 11:11:47.156] [main/INFO] [net.minecraftforge.coremod.CoreMod.placebo/COREMODLOG]: Patching ItemStack#onItemUse
[05Nov2021 11:11:47.301] [main/WARN] [mixin/]: @Mixin target net/minecraft/world/gen/feature/structure/MineshaftPieces$Piece is public in charm.mixins.json:accessor.MineshaftPiecesAccessor and should be specified in value
[05Nov2021 11:11:47.407] [main/WARN] [mixin/]: @Mixin target net/minecraft/block/AbstractBlock$AbstractBlockState$Cache is public in ferritecore.blockstatecache.mixin.json:BlockStateCacheMixin and should be specified in value
[05Nov2021 11:11:48.494] [main/INFO] [net.minecraftforge.coremod.CoreMod.placebo/COREMODLOG]: Patching BlockModelShapes#getModelLocation
[05Nov2021 11:11:48.658] [main/INFO] [net.minecraftforge.coremod.CoreMod.placebo/COREMODLOG]: Patching LivingEntity#attackEntityFrom
[05Nov2021 11:11:48.742] [main/WARN] [Forgery/]: Mixin com.unascribed.fabrication.mixin.f_balance.mobs_dont_drop_ingots.MixinLivingEntity failed to apply! Force-disabling *.mobs_dont_drop_ingots
[05Nov2021 11:11:48.822] [main/WARN] [mixin/]: Static binding violation: PRIVATE @Overwrite method func_228441_a_ in magnesium.mixins.json:features.chunk_rendering.MixinWorldRenderer cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[05Nov2021 11:11:48.822] [main/WARN] [mixin/]: Static binding violation: PRIVATE @Overwrite method func_228437_a_ in magnesium.mixins.json:features.chunk_rendering.MixinWorldRenderer cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[05Nov2021 11:11:48.883] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[05Nov2021 11:11:48.883] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[05Nov2021 11:11:48.884] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:307)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:425)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.client.main.Main.main(Main.java:122)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	... 10 more
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetFancyWeather()Z in magnesium.mixins.json:features.options.MixinWorldRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap magnesium.refmap.json
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject$failsoft(gist.github.com/517e2d6d4c6a75303721b7e2e995a9f8)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[05Nov2021 11:11:48.885] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	... 25 more
```
</details>

Other info:
* **Sugar & Spice Version**: `3.6.5`
* **Launcher**: GDLauncher 
* **Forge**: `36.2.4`

**Comment by evanbones** [comment]
Oh whoops, looks like I forgot to change the name of the Magnesium jar in the script. To fix this, just manually delete Magnesium from the mods folder.  This'll be fixed in the next update, thanks for the report!
